-- Lexicon Media Files Schema
-- This creates the media_files and file_data tables in the shared mydb database

CREATE TABLE IF NOT EXISTS media_files (
    id INT PRIMARY KEY,
    filename VARCHAR(500) NOT NULL,
    original_filename VARCHAR(500),
    content_type VARCHAR(100),
    file_size BIGINT,
    file_path VARCHAR(1000) NOT NULL,
    uploaded_by INT NOT NULL,
    upload_date TIMESTAMP NOT NULL,
    title VARCHAR(500),
    description VARCHAR(2000),
    is_public BOOLEAN DEFAULT FALSE,
    media_type VARCHAR(50),
    source_url VARCHAR(1000)
);

-- Table for storing actual file binary data
CREATE TABLE IF NOT EXISTS file_data (
    media_file_id INT PRIMARY KEY,
    data VARBINARY(2147483647),
    FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE CASCADE
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_media_uploaded_by ON media_files(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_media_is_public ON media_files(is_public);
CREATE INDEX IF NOT EXISTS idx_media_type ON media_files(media_type);

-- Table for tracking playback positions in audiobooks/media
CREATE TABLE IF NOT EXISTS playback_positions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    media_file_id INT NOT NULL,
    position DOUBLE NOT NULL,
    duration DOUBLE NOT NULL,
    last_updated TIMESTAMP NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    UNIQUE(user_id, media_file_id),
    FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE CASCADE
);

-- Indexes for playback positions
CREATE INDEX IF NOT EXISTS idx_playback_user ON playback_positions(user_id);
CREATE INDEX IF NOT EXISTS idx_playback_media ON playback_positions(media_file_id);
CREATE INDEX IF NOT EXISTS idx_playback_updated ON playback_positions(last_updated DESC);
