package lexicon.scripts;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 * Script to create playlist tables in HSQLDB
 * Run this once to initialize the schema
 */
public class CreatePlaylistTables {
    
    public static void main(String[] args) {
        String url = "jdbc:hsqldb:hsql://localhost:9002/mydb";
        String user = "SA";
        String password = "";
        
        try {
            // Load HSQLDB driver
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
        } catch (ClassNotFoundException e) {
            System.err.println("HSQLDB driver not found");
            e.printStackTrace();
            return;
        }
        
        try (Connection conn = DriverManager.getConnection(url, user, password);
             Statement stmt = conn.createStatement()) {
            
            System.out.println("Connected to database");
            
            // Create playlists table
            String createPlaylistsTable = 
                "CREATE TABLE IF NOT EXISTS playlists (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(500) NOT NULL, " +
                "description VARCHAR(2000), " +
                "is_public BOOLEAN DEFAULT false, " +
                "created_by INT NOT NULL, " +
                "media_type VARCHAR(50) NOT NULL, " +
                "created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE)";
            
            stmt.execute(createPlaylistsTable);
            System.out.println("Created playlists table");
            
            // Create playlist_items table
            String createPlaylistItemsTable = 
                "CREATE TABLE IF NOT EXISTS playlist_items (" +
                "playlist_id INT NOT NULL, " +
                "media_file_id INT NOT NULL, " +
                "position INT NOT NULL, " +
                "PRIMARY KEY (playlist_id, media_file_id), " +
                "FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE, " +
                "FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE CASCADE)";
            
            stmt.execute(createPlaylistItemsTable);
            System.out.println("Created playlist_items table");
            
            System.out.println("\nPlaylist tables created successfully!");
            
        } catch (Exception e) {
            System.err.println("Error creating tables:");
            e.printStackTrace();
        }
    }
}
