package lexicon.data;

import lexicon.object.Notification;
import lexicon.object.NotificationPrefs;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * HSQLDB implementation for notification storage + per-user preferences.
 * Follows the same DriverManager pattern as HSQLMessageDatabase, and creates its
 * own tables on startup (the per-repository pattern used across this codebase).
 */
@Repository
public class HSQLNotificationDatabase implements INotificationDatabase {

    private static final LocalDateTime EPOCH = LocalDateTime.of(1970, 1, 1, 0, 0);

    private final String DATABASE_URL =
            System.getProperty("database.url",
                    System.getenv().getOrDefault("DATABASE_URL", "jdbc:hsqldb:hsql://localhost:9002/mydb"));

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, "SA", "");
    }

    @PostConstruct
    public void initializeSchema() {
        String notifications =
                "CREATE TABLE IF NOT EXISTS notifications (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "target_user_id INT, " +
                "type VARCHAR(20) NOT NULL, " +
                "title VARCHAR(255) NOT NULL, " +
                "body VARCHAR(1000), " +
                "source VARCHAR(20) DEFAULT 'mumble', " +
                "from_username VARCHAR(255), " +
                "from_user_id INT, " +
                "channel_id INT, " +
                "link VARCHAR(500), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
        String notifIndex =
                "CREATE INDEX IF NOT EXISTS idx_notif_target_time ON notifications(target_user_id, created_at)";
        String prefs =
                "CREATE TABLE IF NOT EXISTS notification_prefs (" +
                "user_id INT PRIMARY KEY, " +
                "enable_message BOOLEAN DEFAULT TRUE, " +
                "enable_voice_join BOOLEAN DEFAULT TRUE, " +
                "enable_mention BOOLEAN DEFAULT TRUE, " +
                "enable_music BOOLEAN DEFAULT FALSE, " +
                "enable_push BOOLEAN DEFAULT TRUE, " +
                "last_read_at TIMESTAMP)";
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(notifications);
            stmt.execute(notifIndex);
            stmt.execute(prefs);
            System.out.println("✓ Notification tables initialized");
        } catch (SQLException e) {
            System.err.println("⚠ Could not initialize notification tables: " + e.getMessage());
        }
    }

    @Override
    public long insert(Notification n) {
        String sql = "INSERT INTO notifications (target_user_id, type, title, body, source, from_username, from_user_id, channel_id, link, created_at) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            setNullableInt(stmt, 1, n.getTargetUserId());
            stmt.setString(2, n.getType());
            stmt.setString(3, n.getTitle());
            stmt.setString(4, n.getBody());
            stmt.setString(5, n.getSource() != null ? n.getSource() : "mumble");
            stmt.setString(6, n.getFromUsername());
            setNullableInt(stmt, 7, n.getFromUserId());
            setNullableInt(stmt, 8, n.getChannelId());
            stmt.setString(9, n.getLink());
            stmt.setTimestamp(10, Timestamp.valueOf(
                    n.getCreatedAt() != null ? n.getCreatedAt() : LocalDateTime.now()));
            stmt.executeUpdate();
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) return keys.getLong(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Failed to insert notification: " + e.getMessage(), e);
        }
        return -1;
    }

    @Override
    public List<Notification> listForUser(int userId, int limit, Long beforeId) {
        List<Notification> out = new ArrayList<>();
        StringBuilder sql = new StringBuilder(
                "SELECT * FROM notifications WHERE (target_user_id = ? OR target_user_id IS NULL) " +
                "AND (from_user_id IS NULL OR from_user_id <> ?) ");
        if (beforeId != null) sql.append("AND id < ? ");
        sql.append("ORDER BY id DESC LIMIT ?");

        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql.toString())) {
            int i = 1;
            stmt.setInt(i++, userId);
            stmt.setInt(i++, userId);
            if (beforeId != null) stmt.setLong(i++, beforeId);
            stmt.setInt(i, limit);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(map(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    @Override
    public int unreadCount(int userId) {
        NotificationPrefs prefs = getPrefs(userId);
        LocalDateTime lastRead = prefs.getLastReadAt() != null ? prefs.getLastReadAt() : EPOCH;
        String sql = "SELECT COUNT(*) FROM notifications WHERE (target_user_id = ? OR target_user_id IS NULL) " +
                     "AND (from_user_id IS NULL OR from_user_id <> ?) AND created_at > ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, userId);
            stmt.setInt(2, userId);
            stmt.setTimestamp(3, Timestamp.valueOf(lastRead));
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    @Override
    public NotificationPrefs getPrefs(int userId) {
        String sql = "SELECT * FROM notification_prefs WHERE user_id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, userId);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return mapPrefs(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        // No row yet — create defaults and return them.
        NotificationPrefs defaults = new NotificationPrefs();
        defaults.setUserId(userId);
        insertDefaultPrefs(defaults);
        return defaults;
    }

    private void insertDefaultPrefs(NotificationPrefs p) {
        String sql = "INSERT INTO notification_prefs (user_id, enable_message, enable_voice_join, enable_mention, enable_music, enable_push) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, p.getUserId());
            stmt.setBoolean(2, p.isEnableMessage());
            stmt.setBoolean(3, p.isEnableVoiceJoin());
            stmt.setBoolean(4, p.isEnableMention());
            stmt.setBoolean(5, p.isEnableMusic());
            stmt.setBoolean(6, p.isEnablePush());
            stmt.executeUpdate();
        } catch (SQLException e) {
            // Likely a race where the row already exists — safe to ignore.
        }
    }

    @Override
    public void updatePrefs(NotificationPrefs prefs) {
        getPrefs(prefs.getUserId()); // ensure a row exists
        String sql = "UPDATE notification_prefs SET enable_message = ?, enable_voice_join = ?, enable_mention = ?, " +
                     "enable_music = ?, enable_push = ? WHERE user_id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setBoolean(1, prefs.isEnableMessage());
            stmt.setBoolean(2, prefs.isEnableVoiceJoin());
            stmt.setBoolean(3, prefs.isEnableMention());
            stmt.setBoolean(4, prefs.isEnableMusic());
            stmt.setBoolean(5, prefs.isEnablePush());
            stmt.setInt(6, prefs.getUserId());
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void markAllRead(int userId) {
        getPrefs(userId); // ensure a row exists
        String sql = "UPDATE notification_prefs SET last_read_at = ? WHERE user_id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now()));
            stmt.setInt(2, userId);
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<NotificationPrefs> pushRecipientsForType(String type) {
        List<NotificationPrefs> out = new ArrayList<>();
        String column;
        switch (type != null ? type : "") {
            case "message":    column = "enable_message"; break;
            case "voice_join": column = "enable_voice_join"; break;
            case "mention":    column = "enable_mention"; break;
            case "music":      column = "enable_music"; break;
            default:           return out; // unknown type → nobody
        }
        String sql = "SELECT * FROM notification_prefs WHERE enable_push = TRUE AND " + column + " = TRUE";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(mapPrefs(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    // ===== helpers =====

    private void setNullableInt(PreparedStatement stmt, int idx, Integer value) throws SQLException {
        if (value != null) {
            stmt.setInt(idx, value);
        } else {
            stmt.setNull(idx, Types.INTEGER);
        }
    }

    private Notification map(ResultSet rs) throws SQLException {
        Notification n = new Notification();
        n.setId(rs.getLong("id"));
        int target = rs.getInt("target_user_id");
        n.setTargetUserId(rs.wasNull() ? null : target);
        n.setType(rs.getString("type"));
        n.setTitle(rs.getString("title"));
        n.setBody(rs.getString("body"));
        n.setSource(rs.getString("source"));
        n.setFromUsername(rs.getString("from_username"));
        int fromId = rs.getInt("from_user_id");
        n.setFromUserId(rs.wasNull() ? null : fromId);
        int chId = rs.getInt("channel_id");
        n.setChannelId(rs.wasNull() ? null : chId);
        n.setLink(rs.getString("link"));
        Timestamp created = rs.getTimestamp("created_at");
        n.setCreatedAt(created != null ? created.toLocalDateTime() : null);
        return n;
    }

    private NotificationPrefs mapPrefs(ResultSet rs) throws SQLException {
        NotificationPrefs p = new NotificationPrefs();
        p.setUserId(rs.getInt("user_id"));
        p.setEnableMessage(rs.getBoolean("enable_message"));
        p.setEnableVoiceJoin(rs.getBoolean("enable_voice_join"));
        p.setEnableMention(rs.getBoolean("enable_mention"));
        p.setEnableMusic(rs.getBoolean("enable_music"));
        p.setEnablePush(rs.getBoolean("enable_push"));
        Timestamp lastRead = rs.getTimestamp("last_read_at");
        p.setLastReadAt(lastRead != null ? lastRead.toLocalDateTime() : null);
        return p;
    }
}
