package lexicon.data;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import lexicon.object.MediaFile;
import lexicon.object.MediaType;
import lexicon.object.Playlist;
import lexicon.object.PlaylistItem;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Repository
public class HSQLPlaylistDatabase implements IPlaylistDatabase {
    
    private final String DATABASE_URL = "jdbc:hsqldb:hsql://localhost:9002/mydb";
    private final HikariDataSource dataSource;
    
    @Autowired
    private IMediaDatabase mediaDatabase;
    
    public HSQLPlaylistDatabase() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(DATABASE_URL);
        config.setUsername("SA");
        config.setPassword("");
        config.setMaximumPoolSize(10);
        config.setMinimumIdle(2);
        config.setConnectionTimeout(5000);
        config.setIdleTimeout(60000);
        config.setMaxLifetime(300000);
        config.setPoolName("playlist-db");
        this.dataSource = new HikariDataSource(config);
    }
    
    @PreDestroy
    public void cleanup() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
        }
    }
    
    private Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }
    
    @PostConstruct
    private void initializeSchema() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            // Create playlists table
            String createPlaylistsTable = 
                "CREATE TABLE IF NOT EXISTS playlists (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(500) NOT NULL, " +
                "description VARCHAR(2000), " +
                "is_public BOOLEAN DEFAULT false, " +
                "created_by INT NOT NULL, " +
                "media_type VARCHAR(50) NOT NULL, " +
                "created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
            stmt.execute(createPlaylistsTable);
            
            // Create playlist_items table
            String createPlaylistItemsTable = 
                "CREATE TABLE IF NOT EXISTS playlist_items (" +
                "playlist_id INT NOT NULL, " +
                "media_file_id INT NOT NULL, " +
                "position INT NOT NULL, " +
                "PRIMARY KEY (playlist_id, media_file_id), " +
                "FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE, " +
                "FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE CASCADE)";
            stmt.execute(createPlaylistItemsTable);
            
            System.out.println("✓ Playlist database schema initialized successfully");
        } catch (SQLException e) {
            System.err.println("Error initializing playlist schema:");
            e.printStackTrace();
        }

        // Add indexes for performance
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            try { stmt.execute("CREATE INDEX IF NOT EXISTS idx_playlists_created_by ON playlists(created_by)"); } catch (SQLException ignored) {}
            try { stmt.execute("CREATE INDEX IF NOT EXISTS idx_playlists_public ON playlists(is_public)"); } catch (SQLException ignored) {}
            try { stmt.execute("CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist ON playlist_items(playlist_id, position)"); } catch (SQLException ignored) {}
            System.out.println("✓ Playlist indexes verified");
        } catch (SQLException e) {
            System.err.println("Error creating playlist indexes: " + e.getMessage());
        }
    }
    
    @Override
    public int createPlaylist(Playlist playlist) {
        String sql = "INSERT INTO playlists (name, description, is_public, created_by, media_type, created_date) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            stmt.setString(1, playlist.getName());
            stmt.setString(2, playlist.getDescription());
            stmt.setBoolean(3, playlist.isPublic());
            stmt.setInt(4, playlist.getCreatedBy());
            stmt.setString(5, playlist.getMediaType().name());
            stmt.setTimestamp(6, Timestamp.valueOf(playlist.getCreatedDate()));
            
            int affectedRows = stmt.executeUpdate();
            
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        return generatedKeys.getInt(1);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1;
    }
    
    @Override
    public Playlist getPlaylistById(int playlistId) {
        String sql = "SELECT * FROM playlists WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                return mapResultSetToPlaylist(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }
    
    @Override
    public Playlist getPlaylistWithItems(int playlistId) {
        Playlist playlist = getPlaylistById(playlistId);
        if (playlist == null) return null;

        // Single JOIN query instead of N+1 per-item getMediaFile calls
        String sql = "SELECT pi.playlist_id, pi.media_file_id, pi.position, " +
                "mf.id, mf.filename, mf.original_filename, mf.content_type, mf.file_size, " +
                "mf.file_path, mf.uploaded_by, mf.upload_date, mf.title, mf.description, " +
                "mf.is_public, mf.media_type, mf.source_url " +
                "FROM playlist_items pi " +
                "JOIN media_files mf ON pi.media_file_id = mf.id " +
                "WHERE pi.playlist_id = ? ORDER BY pi.position ASC";

        List<PlaylistItem> items = new ArrayList<>();
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, playlistId);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                PlaylistItem item = new PlaylistItem();
                item.setPlaylistId(rs.getInt("playlist_id"));
                item.setMediaFileId(rs.getInt("media_file_id"));
                item.setPosition(rs.getInt("position"));

                MediaFile mf = new MediaFile(
                    rs.getInt("id"), rs.getString("filename"), rs.getString("original_filename"),
                    rs.getString("content_type"), rs.getLong("file_size"), rs.getString("file_path"),
                    rs.getInt("uploaded_by"), rs.getString("title"), rs.getString("description"),
                    rs.getBoolean("is_public")
                );
                Timestamp ts = rs.getTimestamp("upload_date");
                if (ts != null) mf.setUploadDate(ts.toLocalDateTime());
                String mt = rs.getString("media_type");
                if (mt != null) mf.setMediaType(MediaType.fromString(mt));
                mf.setSourceUrl(rs.getString("source_url"));
                item.setMediaFile(mf);

                items.add(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        playlist.setItems(items);
        return playlist;
    }
    
    @Override
    public List<Playlist> getPlaylistsByUser(int userId) {
        String sql = "SELECT * FROM playlists WHERE created_by = ? ORDER BY created_date DESC";
        List<Playlist> playlists = new ArrayList<>();
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                playlists.add(mapResultSetToPlaylist(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playlists;
    }
    
    @Override
    public List<Playlist> getPublicPlaylists() {
        String sql = "SELECT p.*, (SELECT COUNT(*) FROM playlist_items pi WHERE pi.playlist_id = p.id) AS item_count " +
                     "FROM playlists p WHERE p.is_public = true ORDER BY p.created_date DESC";
        List<Playlist> playlists = new ArrayList<>();
        
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {
            
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                Playlist p = mapResultSetToPlaylist(rs);
                p.setItemCount(rs.getInt("item_count"));
                playlists.add(p);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playlists;
    }
    
    @Override
    public boolean updatePlaylist(Playlist playlist) {
        String sql = "UPDATE playlists SET name = ?, description = ?, is_public = ?, media_type = ? WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setString(1, playlist.getName());
            stmt.setString(2, playlist.getDescription());
            stmt.setBoolean(3, playlist.isPublic());
            stmt.setString(4, playlist.getMediaType().name());
            stmt.setInt(5, playlist.getId());
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean deletePlaylist(int playlistId) {
        // Items will be deleted automatically due to CASCADE
        String sql = "DELETE FROM playlists WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean addItemToPlaylist(int playlistId, int mediaFileId, int position) {
        String sql = "INSERT INTO playlist_items (playlist_id, media_file_id, position) VALUES (?, ?, ?)";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            stmt.setInt(2, mediaFileId);
            stmt.setInt(3, position);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean removeItemFromPlaylist(int playlistId, int mediaFileId) {
        String sql = "DELETE FROM playlist_items WHERE playlist_id = ? AND media_file_id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            stmt.setInt(2, mediaFileId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public List<PlaylistItem> getPlaylistItems(int playlistId) {
        String sql = "SELECT * FROM playlist_items WHERE playlist_id = ? ORDER BY position ASC";
        List<PlaylistItem> items = new ArrayList<>();
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                PlaylistItem item = new PlaylistItem();
                item.setPlaylistId(rs.getInt("playlist_id"));
                item.setMediaFileId(rs.getInt("media_file_id"));
                item.setPosition(rs.getInt("position"));
                items.add(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return items;
    }
    
    @Override
    public boolean updateItemPosition(int playlistId, int mediaFileId, int newPosition) {
        String sql = "UPDATE playlist_items SET position = ? WHERE playlist_id = ? AND media_file_id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, newPosition);
            stmt.setInt(2, playlistId);
            stmt.setInt(3, mediaFileId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean reorderPlaylist(int playlistId, List<Integer> mediaFileIds) {
        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            
            try {
                for (int i = 0; i < mediaFileIds.size(); i++) {
                    updateItemPosition(playlistId, mediaFileIds.get(i), i);
                }
                conn.commit();
                return true;
            } catch (SQLException e) {
                conn.rollback();
                e.printStackTrace();
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private Playlist mapResultSetToPlaylist(ResultSet rs) throws SQLException {
        Playlist playlist = new Playlist();
        playlist.setId(rs.getInt("id"));
        playlist.setName(rs.getString("name"));
        playlist.setDescription(rs.getString("description"));
        playlist.setPublic(rs.getBoolean("is_public"));
        playlist.setCreatedBy(rs.getInt("created_by"));
        
        String mediaTypeStr = rs.getString("media_type");
        if (mediaTypeStr != null) {
            playlist.setMediaType(MediaType.valueOf(mediaTypeStr));
        }
        
        Timestamp timestamp = rs.getTimestamp("created_date");
        if (timestamp != null) {
            playlist.setCreatedDate(timestamp.toLocalDateTime());
        }
        
        return playlist;
    }

    /**
     * Bulk query: get all distinct media file IDs that appear in any public playlist.
     */
    @Override
    public List<MediaFile> getMediaInPublicPlaylists() {
        String sql = "SELECT DISTINCT mf.id, mf.filename, mf.original_filename, mf.content_type, mf.file_size, " +
                "mf.file_path, mf.uploaded_by, mf.upload_date, mf.title, mf.description, " +
                "mf.is_public, mf.media_type, mf.source_url " +
                "FROM playlist_items pi " +
                "JOIN playlists p ON pi.playlist_id = p.id " +
                "JOIN media_files mf ON pi.media_file_id = mf.id " +
                "WHERE p.is_public = true";
        List<MediaFile> results = new ArrayList<>();
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                MediaFile mf = new MediaFile(
                    rs.getInt("id"), rs.getString("filename"), rs.getString("original_filename"),
                    rs.getString("content_type"), rs.getLong("file_size"), rs.getString("file_path"),
                    rs.getInt("uploaded_by"), rs.getString("title"), rs.getString("description"),
                    rs.getBoolean("is_public")
                );
                Timestamp ts = rs.getTimestamp("upload_date");
                if (ts != null) mf.setUploadDate(ts.toLocalDateTime());
                String mt = rs.getString("media_type");
                if (mt != null) mf.setMediaType(MediaType.fromString(mt));
                mf.setSourceUrl(rs.getString("source_url"));
                results.add(mf);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return results;
    }

    /**
     * Check if a specific media file appears in any public playlist (single query, no N+1).
     */
    @Override
    public boolean isMediaInAnyPublicPlaylist(int mediaFileId) {
        String sql = "SELECT 1 FROM playlist_items pi " +
                "JOIN playlists p ON pi.playlist_id = p.id " +
                "WHERE p.is_public = true AND pi.media_file_id = ? " +
                "FETCH FIRST 1 ROW ONLY";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, mediaFileId);
            ResultSet rs = stmt.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
}
