package lexicon.data;

import jakarta.annotation.PostConstruct;
import lexicon.object.MediaFile;
import lexicon.object.MediaType;
import lexicon.object.Playlist;
import lexicon.object.PlaylistItem;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Repository
public class HSQLPlaylistDatabase implements IPlaylistDatabase {
    
    // Use same database as media files
    private final String DATABASE_URL = "jdbc:hsqldb:hsql://localhost:9002/mydb";
    
    @Autowired
    private IMediaDatabase mediaDatabase;
    
    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, "SA", "");
    }
    
    @PostConstruct
    private void initializeSchema() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            // Create playlists table
            String createPlaylistsTable = 
                "CREATE TABLE IF NOT EXISTS playlists (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(500) NOT NULL, " +
                "description VARCHAR(2000), " +
                "is_public BOOLEAN DEFAULT false, " +
                "created_by INT NOT NULL, " +
                "media_type VARCHAR(50) NOT NULL, " +
                "created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
            stmt.execute(createPlaylistsTable);
            
            // Create playlist_items table
            String createPlaylistItemsTable = 
                "CREATE TABLE IF NOT EXISTS playlist_items (" +
                "playlist_id INT NOT NULL, " +
                "media_file_id INT NOT NULL, " +
                "position INT NOT NULL, " +
                "PRIMARY KEY (playlist_id, media_file_id), " +
                "FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE, " +
                "FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE CASCADE)";
            stmt.execute(createPlaylistItemsTable);
            
            System.out.println("✓ Playlist database schema initialized successfully");
        } catch (SQLException e) {
            System.err.println("Error initializing playlist schema:");
            e.printStackTrace();
        }
    }
    
    @Override
    public int createPlaylist(Playlist playlist) {
        String sql = "INSERT INTO playlists (name, description, is_public, created_by, media_type, created_date) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            stmt.setString(1, playlist.getName());
            stmt.setString(2, playlist.getDescription());
            stmt.setBoolean(3, playlist.isPublic());
            stmt.setInt(4, playlist.getCreatedBy());
            stmt.setString(5, playlist.getMediaType().name());
            stmt.setTimestamp(6, Timestamp.valueOf(playlist.getCreatedDate()));
            
            int affectedRows = stmt.executeUpdate();
            
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        return generatedKeys.getInt(1);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1;
    }
    
    @Override
    public Playlist getPlaylistById(int playlistId) {
        String sql = "SELECT * FROM playlists WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                return mapResultSetToPlaylist(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }
    
    @Override
    public Playlist getPlaylistWithItems(int playlistId) {
        Playlist playlist = getPlaylistById(playlistId);
        if (playlist != null) {
            List<PlaylistItem> items = getPlaylistItems(playlistId);
            
            // Populate each item with full media file info
            for (PlaylistItem item : items) {
                MediaFile mediaFile = mediaDatabase.getMediaFile(item.getMediaFileId());
                item.setMediaFile(mediaFile);
            }
            
            playlist.setItems(items);
        }
        return playlist;
    }
    
    @Override
    public List<Playlist> getPlaylistsByUser(int userId) {
        String sql = "SELECT * FROM playlists WHERE created_by = ? ORDER BY created_date DESC";
        List<Playlist> playlists = new ArrayList<>();
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                playlists.add(mapResultSetToPlaylist(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playlists;
    }
    
    @Override
    public List<Playlist> getPublicPlaylists() {
        String sql = "SELECT * FROM playlists WHERE is_public = true ORDER BY created_date DESC";
        List<Playlist> playlists = new ArrayList<>();
        
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {
            
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                playlists.add(mapResultSetToPlaylist(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playlists;
    }
    
    @Override
    public boolean updatePlaylist(Playlist playlist) {
        String sql = "UPDATE playlists SET name = ?, description = ?, is_public = ?, media_type = ? WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setString(1, playlist.getName());
            stmt.setString(2, playlist.getDescription());
            stmt.setBoolean(3, playlist.isPublic());
            stmt.setString(4, playlist.getMediaType().name());
            stmt.setInt(5, playlist.getId());
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean deletePlaylist(int playlistId) {
        // Items will be deleted automatically due to CASCADE
        String sql = "DELETE FROM playlists WHERE id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean addItemToPlaylist(int playlistId, int mediaFileId, int position) {
        String sql = "INSERT INTO playlist_items (playlist_id, media_file_id, position) VALUES (?, ?, ?)";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            stmt.setInt(2, mediaFileId);
            stmt.setInt(3, position);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean removeItemFromPlaylist(int playlistId, int mediaFileId) {
        String sql = "DELETE FROM playlist_items WHERE playlist_id = ? AND media_file_id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            stmt.setInt(2, mediaFileId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public List<PlaylistItem> getPlaylistItems(int playlistId) {
        String sql = "SELECT * FROM playlist_items WHERE playlist_id = ? ORDER BY position ASC";
        List<PlaylistItem> items = new ArrayList<>();
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, playlistId);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                PlaylistItem item = new PlaylistItem();
                item.setPlaylistId(rs.getInt("playlist_id"));
                item.setMediaFileId(rs.getInt("media_file_id"));
                item.setPosition(rs.getInt("position"));
                items.add(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return items;
    }
    
    @Override
    public boolean updateItemPosition(int playlistId, int mediaFileId, int newPosition) {
        String sql = "UPDATE playlist_items SET position = ? WHERE playlist_id = ? AND media_file_id = ?";
        
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, newPosition);
            stmt.setInt(2, playlistId);
            stmt.setInt(3, mediaFileId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    @Override
    public boolean reorderPlaylist(int playlistId, List<Integer> mediaFileIds) {
        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            
            try {
                for (int i = 0; i < mediaFileIds.size(); i++) {
                    updateItemPosition(playlistId, mediaFileIds.get(i), i);
                }
                conn.commit();
                return true;
            } catch (SQLException e) {
                conn.rollback();
                e.printStackTrace();
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private Playlist mapResultSetToPlaylist(ResultSet rs) throws SQLException {
        Playlist playlist = new Playlist();
        playlist.setId(rs.getInt("id"));
        playlist.setName(rs.getString("name"));
        playlist.setDescription(rs.getString("description"));
        playlist.setPublic(rs.getBoolean("is_public"));
        playlist.setCreatedBy(rs.getInt("created_by"));
        
        String mediaTypeStr = rs.getString("media_type");
        if (mediaTypeStr != null) {
            playlist.setMediaType(MediaType.valueOf(mediaTypeStr));
        }
        
        Timestamp timestamp = rs.getTimestamp("created_date");
        if (timestamp != null) {
            playlist.setCreatedDate(timestamp.toLocalDateTime());
        }
        
        return playlist;
    }
}
