package lexicon.data;

import lexicon.object.Event;
import lexicon.object.Poll;
import lexicon.object.PollOption;
import lexicon.object.PollVote;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * HSQLDB implementation for events, polls, poll options, and poll votes.
 * Follows the same DriverManager pattern as HSQLNotificationDatabase, and
 * creates its own tables on startup (the per-repository pattern used across
 * this codebase). Pure CRUD only — no joins that compute vote counts or
 * voter lists; that assembly belongs to EventManager (logic layer).
 */
@Repository
public class HSQLEventDatabase implements IEventDatabase {

    private final String DATABASE_URL =
            System.getProperty("database.url",
                    System.getenv().getOrDefault("DATABASE_URL", "jdbc:hsqldb:hsql://localhost:9002/mydb"));

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, "SA", "");
    }

    @PostConstruct
    public void initializeSchema() {
        String events =
                "CREATE TABLE IF NOT EXISTS events (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "title VARCHAR(255) NOT NULL, " +
                "description VARCHAR(2000), " +
                "event_date DATE, " +
                "created_by_user_id INT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
        String polls =
                "CREATE TABLE IF NOT EXISTS polls (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "event_id BIGINT NOT NULL, " +
                "question VARCHAR(500) NOT NULL, " +
                "allow_add_options BOOLEAN DEFAULT TRUE, " +
                "display_order INT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE)";
        String pollsIndex =
                "CREATE INDEX IF NOT EXISTS idx_polls_event ON polls(event_id)";
        String pollOptions =
                "CREATE TABLE IF NOT EXISTS poll_options (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "poll_id BIGINT NOT NULL, " +
                "text VARCHAR(500) NOT NULL, " +
                "added_by_name VARCHAR(255), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE)";
        String optionsIndex =
                "CREATE INDEX IF NOT EXISTS idx_options_poll ON poll_options(poll_id)";
        String pollVotes =
                "CREATE TABLE IF NOT EXISTS poll_votes (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "option_id BIGINT NOT NULL, " +
                "voter_key VARCHAR(100) NOT NULL, " +
                "voter_name VARCHAR(255) NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "UNIQUE(option_id, voter_key), " +
                "FOREIGN KEY (option_id) REFERENCES poll_options(id) ON DELETE CASCADE)";
        String votesIndex =
                "CREATE INDEX IF NOT EXISTS idx_votes_voter ON poll_votes(voter_key)";
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(events);
            stmt.execute(polls);
            stmt.execute(pollsIndex);
            stmt.execute(pollOptions);
            stmt.execute(optionsIndex);
            stmt.execute(pollVotes);
            stmt.execute(votesIndex);
            System.out.println("✓ Event tables initialized");
        } catch (SQLException e) {
            System.err.println("⚠ Could not initialize event tables: " + e.getMessage());
        }
    }

    @Override
    public long insertEvent(Event e) {
        String sql = "INSERT INTO events (title, description, event_date, created_by_user_id, created_at) " +
                     "VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, e.getTitle());
            stmt.setString(2, e.getDescription());
            setNullableDate(stmt, 3, e.getEventDate());
            setNullableInt(stmt, 4, e.getCreatedByUserId());
            stmt.setTimestamp(5, Timestamp.valueOf(
                    e.getCreatedAt() != null ? e.getCreatedAt() : LocalDateTime.now()));
            stmt.executeUpdate();
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) return keys.getLong(1);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            throw new RuntimeException("Failed to insert event: " + ex.getMessage(), ex);
        }
        return -1;
    }

    @Override
    public List<Event> getAllEvents() {
        List<Event> out = new ArrayList<>();
        String sql = "SELECT * FROM events ORDER BY created_at DESC";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) out.add(mapEvent(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    @Override
    public Event getEventById(long id) {
        String sql = "SELECT * FROM events WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return mapEvent(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public long insertPoll(Poll p) {
        String sql = "INSERT INTO polls (event_id, question, allow_add_options, display_order, created_at) " +
                     "VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            stmt.setLong(1, p.getEventId());
            stmt.setString(2, p.getQuestion());
            stmt.setBoolean(3, p.isAllowAddOptions());
            stmt.setInt(4, p.getDisplayOrder());
            stmt.setTimestamp(5, Timestamp.valueOf(
                    p.getCreatedAt() != null ? p.getCreatedAt() : LocalDateTime.now()));
            stmt.executeUpdate();
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) return keys.getLong(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Failed to insert poll: " + e.getMessage(), e);
        }
        return -1;
    }

    @Override
    public List<Poll> getPollsByEventId(long eventId) {
        List<Poll> out = new ArrayList<>();
        String sql = "SELECT * FROM polls WHERE event_id = ? ORDER BY display_order, id";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, eventId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(mapPoll(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    @Override
    public Poll getPollById(long id) {
        String sql = "SELECT * FROM polls WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return mapPoll(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public long insertOption(PollOption o) {
        String sql = "INSERT INTO poll_options (poll_id, text, added_by_name, created_at) " +
                     "VALUES (?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            stmt.setLong(1, o.getPollId());
            stmt.setString(2, o.getText());
            stmt.setString(3, o.getAddedByName());
            stmt.setTimestamp(4, Timestamp.valueOf(
                    o.getCreatedAt() != null ? o.getCreatedAt() : LocalDateTime.now()));
            stmt.executeUpdate();
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) return keys.getLong(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Failed to insert poll option: " + e.getMessage(), e);
        }
        return -1;
    }

    @Override
    public List<PollOption> getOptionsByPollId(long pollId) {
        List<PollOption> out = new ArrayList<>();
        String sql = "SELECT * FROM poll_options WHERE poll_id = ? ORDER BY id";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, pollId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(mapOption(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    @Override
    public void insertVote(long optionId, String voterKey, String voterName) {
        String checkSql = "SELECT id FROM poll_votes WHERE option_id = ? AND voter_key = ?";
        String insertSql = "INSERT INTO poll_votes (option_id, voter_key, voter_name, created_at) " +
                            "VALUES (?, ?, ?, ?)";
        try (Connection conn = getConnection()) {
            try (PreparedStatement check = conn.prepareStatement(checkSql)) {
                check.setLong(1, optionId);
                check.setString(2, voterKey);
                try (ResultSet rs = check.executeQuery()) {
                    if (rs.next()) return; // already voted — idempotent no-op
                }
            }
            try (PreparedStatement insert = conn.prepareStatement(insertSql)) {
                insert.setLong(1, optionId);
                insert.setString(2, voterKey);
                insert.setString(3, voterName);
                insert.setTimestamp(4, Timestamp.valueOf(LocalDateTime.now()));
                insert.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void deleteVote(long optionId, String voterKey) {
        String sql = "DELETE FROM poll_votes WHERE option_id = ? AND voter_key = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, optionId);
            stmt.setString(2, voterKey);
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<PollVote> getVotesByOptionId(long optionId) {
        List<PollVote> out = new ArrayList<>();
        String sql = "SELECT * FROM poll_votes WHERE option_id = ? ORDER BY id";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, optionId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(mapVote(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    @Override
    public List<Long> getVotedOptionIds(String voterKey, List<Long> optionIds) {
        List<Long> out = new ArrayList<>();
        if (optionIds == null || optionIds.isEmpty()) return out;

        StringBuilder placeholders = new StringBuilder();
        for (int i = 0; i < optionIds.size(); i++) {
            if (i > 0) placeholders.append(", ");
            placeholders.append("?");
        }
        String sql = "SELECT option_id FROM poll_votes WHERE voter_key = ? AND option_id IN (" +
                     placeholders + ")";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, voterKey);
            int i = 2;
            for (Long optionId : optionIds) {
                stmt.setLong(i++, optionId);
            }
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) out.add(rs.getLong("option_id"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return out;
    }

    // ===== helpers =====

    private void setNullableInt(PreparedStatement stmt, int idx, Integer value) throws SQLException {
        if (value != null) {
            stmt.setInt(idx, value);
        } else {
            stmt.setNull(idx, Types.INTEGER);
        }
    }

    private void setNullableDate(PreparedStatement stmt, int idx, LocalDate value) throws SQLException {
        if (value != null) {
            stmt.setDate(idx, Date.valueOf(value));
        } else {
            stmt.setNull(idx, Types.DATE);
        }
    }

    private Event mapEvent(ResultSet rs) throws SQLException {
        Event e = new Event();
        e.setId(rs.getLong("id"));
        e.setTitle(rs.getString("title"));
        e.setDescription(rs.getString("description"));
        Date eventDate = rs.getDate("event_date");
        e.setEventDate(eventDate != null ? eventDate.toLocalDate() : null);
        int createdBy = rs.getInt("created_by_user_id");
        e.setCreatedByUserId(rs.wasNull() ? null : createdBy);
        Timestamp created = rs.getTimestamp("created_at");
        e.setCreatedAt(created != null ? created.toLocalDateTime() : null);
        return e;
    }

    private Poll mapPoll(ResultSet rs) throws SQLException {
        Poll p = new Poll();
        p.setId(rs.getLong("id"));
        p.setEventId(rs.getLong("event_id"));
        p.setQuestion(rs.getString("question"));
        p.setAllowAddOptions(rs.getBoolean("allow_add_options"));
        p.setDisplayOrder(rs.getInt("display_order"));
        Timestamp created = rs.getTimestamp("created_at");
        p.setCreatedAt(created != null ? created.toLocalDateTime() : null);
        return p;
    }

    private PollOption mapOption(ResultSet rs) throws SQLException {
        PollOption o = new PollOption();
        o.setId(rs.getLong("id"));
        o.setPollId(rs.getLong("poll_id"));
        o.setText(rs.getString("text"));
        o.setAddedByName(rs.getString("added_by_name"));
        Timestamp created = rs.getTimestamp("created_at");
        o.setCreatedAt(created != null ? created.toLocalDateTime() : null);
        return o;
    }

    private PollVote mapVote(ResultSet rs) throws SQLException {
        PollVote v = new PollVote();
        v.setId(rs.getLong("id"));
        v.setOptionId(rs.getLong("option_id"));
        v.setVoterKey(rs.getString("voter_key"));
        v.setVoterName(rs.getString("voter_name"));
        Timestamp created = rs.getTimestamp("created_at");
        v.setCreatedAt(created != null ? created.toLocalDateTime() : null);
        return v;
    }
}
