package lexicon.data;

import lexicon.object.MobileToken;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;
import java.sql.*;
import java.time.LocalDateTime;

/**
 * HSQLDB implementation of mobile auth token persistence.
 * Mirrors HSQLRememberMeDatabase, and creates its own table on startup
 * (the per-repository pattern used across this codebase).
 */
@Repository
public class HSQLMobileTokenDatabase implements IMobileTokenDatabase {

    private final String DATABASE_URL =
            System.getProperty("database.url",
                    System.getenv().getOrDefault("DATABASE_URL", "jdbc:hsqldb:hsql://localhost:9002/mydb"));

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, "SA", "");
    }

    @PostConstruct
    public void initializeSchema() {
        String table =
                "CREATE TABLE IF NOT EXISTS mobile_tokens (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id INT NOT NULL, " +
                "token_hash VARCHAR(64) NOT NULL, " +
                "expires_at TIMESTAMP NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
        String tokenIndex =
                "CREATE INDEX IF NOT EXISTS idx_mobile_token ON mobile_tokens(token_hash)";
        String userIndex =
                "CREATE INDEX IF NOT EXISTS idx_mobile_user ON mobile_tokens(user_id)";
        String expiresIndex =
                "CREATE INDEX IF NOT EXISTS idx_mobile_expires ON mobile_tokens(expires_at)";
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(table);
            stmt.execute(tokenIndex);
            stmt.execute(userIndex);
            stmt.execute(expiresIndex);
            System.out.println("✓ Mobile token table initialized");
        } catch (SQLException e) {
            System.err.println("⚠ Could not initialize mobile token table: " + e.getMessage());
        }
    }

    @Override
    public void storeToken(int userId, String tokenHash, LocalDateTime expiresAt) {
        try (Connection conn = getConnection()) {
            String sql = "INSERT INTO mobile_tokens (user_id, token_hash, expires_at) VALUES (?, ?, ?)";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, userId);
                stmt.setString(2, tokenHash);
                stmt.setTimestamp(3, Timestamp.valueOf(expiresAt));
                stmt.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to store mobile token: " + e.getMessage(), e);
        }
    }

    @Override
    public MobileToken findByTokenHash(String tokenHash) {
        try (Connection conn = getConnection()) {
            String sql = "SELECT id, user_id, token_hash, expires_at, created_at FROM mobile_tokens WHERE token_hash = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, tokenHash);
                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        return new MobileToken(
                            rs.getInt("id"),
                            rs.getInt("user_id"),
                            rs.getString("token_hash"),
                            rs.getTimestamp("expires_at").toLocalDateTime(),
                            rs.getTimestamp("created_at") != null
                                ? rs.getTimestamp("created_at").toLocalDateTime()
                                : null
                        );
                    }
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to find mobile token: " + e.getMessage(), e);
        }
        return null;
    }

    @Override
    public void deleteById(int tokenId) {
        try (Connection conn = getConnection()) {
            String sql = "DELETE FROM mobile_tokens WHERE id = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, tokenId);
                stmt.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to delete mobile token: " + e.getMessage(), e);
        }
    }

    @Override
    public void deleteByUserId(int userId) {
        try (Connection conn = getConnection()) {
            String sql = "DELETE FROM mobile_tokens WHERE user_id = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, userId);
                stmt.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to delete mobile tokens for user: " + e.getMessage(), e);
        }
    }

    @Override
    public int deleteExpired() {
        try (Connection conn = getConnection()) {
            String sql = "DELETE FROM mobile_tokens WHERE expires_at < CURRENT_TIMESTAMP";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                return stmt.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to delete expired mobile tokens: " + e.getMessage(), e);
        }
    }
}
